import { BiVolumeMute, BiBell, BiSticker, BiMicrophone } from "react-icons/bi";
import { FiSettings, FiEdit, FiSearch } from "react-icons/fi";
import { GoSearch } from "react-icons/go";
import { BsFillCloudUploadFill, BsFillBellFill, BsFillBellSlashFill, BsReverseBackspaceReverse, BsArrowDownCircle, BsEmojiSmile, BsFillFolderFill, BsThreeDots, BsCheck, BsCheckAll, BsInfoCircle, BsFillBrushFill } from "react-icons/bs";
import { ImBin, ImAttachment } from "react-icons/im";
import {
  MdOutlineEditCalendar,
  MdKeyboardArrowUp,
  MdKeyboardArrowDown,
  MdLanguage, 
  MdPhoneCallback, 
  MdOutlineTimer, 
  MdCancel, 
  MdOutlineKeyboardArrowRight, 
  MdCall,
  MdKeyboardArrowLeft,
  MdSend,
  MdOutlineSchedule,
  MdOutlineSearch,
  MdOutlineSearchOff,
} from "react-icons/md";
import { RiMacbookLine, RiLock2Fill, RiNotificationBadgeLine, RiInboxArchiveLine, RiShareForwardFill, RiGroupLine, RiErrorWarningFill } from "react-icons/ri";
import { AiOutlineCloseCircle, AiTwotoneMessage, AiOutlineCalendar, AiOutlineEye, AiOutlineUserAdd } from "react-icons/ai";
import { FaRegComment, FaBroom, FaBullhorn,FaVideo, FaRegComments, FaUserCircle } from "react-icons/fa";
import { VscSettingsGear } from "react-icons/vsc";
import { HiOutlineDatabase } from "react-icons/hi";

export {
  BsFillCloudUploadFill,
  BsReverseBackspaceReverse,
  BsFillBellFill,
  BsFillBellSlashFill,
  BiVolumeMute,
  FiSettings,
  BiBell,
  GoSearch,
  BsThreeDots,
  BsInfoCircle,
  BsEmojiSmile,
  BsArrowDownCircle,
  ImBin,
  ImAttachment,
  MdOutlineEditCalendar,
  MdKeyboardArrowUp,
  MdOutlineSchedule,
  MdKeyboardArrowDown,
  RiInboxArchiveLine,
  AiOutlineCloseCircle,
  AiOutlineCalendar,
  RiShareForwardFill, 
  AiOutlineEye,
  MdSend, 
  FaRegComment,
  MdPhoneCallback,
  MdOutlineTimer,
  FiEdit, 
  FaBullhorn,
  FaVideo,
  RiGroupLine,
  FiSearch,
  MdCancel,
  MdOutlineKeyboardArrowRight, 
  MdOutlineSearchOff,
  MdOutlineSearch,
  AiOutlineUserAdd, 
  AiTwotoneMessage,
  FaRegComments, 
  FaBroom,
  FaUserCircle,
  MdCall,
  BsFillFolderFill, 
  BsFillBrushFill,
  RiMacbookLine, 
  RiLock2Fill, 
  RiNotificationBadgeLine,
  MdLanguage,
  VscSettingsGear,
  HiOutlineDatabase,
  BiSticker,
  MdKeyboardArrowLeft,
  RiErrorWarningFill,
  BiMicrophone,
  BsCheck, 
  BsCheckAll,
};
